module.exports = {
	BG_COLOR_FIELD: function (defaultColor) {
		return {
			type: 'colorpicker',
			label: 'Background color',
			id: 'bg',
			default: defaultColor,
		}
	},
	FG_COLOR_FIELD: function (defaultColor) {
		return {
			type: 'colorpicker',
			label: 'Foreground color',
			id: 'fg',
			default: defaultColor,
		}
	},
	CHOICES_SOURCES: [
		{ id: 'tuner', label: 'Tuner' },
		{ id: 'input_1', label: 'Input 1' },
		{ id: 'input_2', label: 'Input 2' },
		{ id: 'input_3', label: 'Input 3' },
		{ id: 'input_4', label: 'Input 4' },
		{ id: 'input_5', label: 'Input 5' },
		{ id: 'input_6', label: 'Input 6' },
		{ id: 'input_7', label: 'Input 7' },
		{ id: 'input_8', label: 'Input 8' },
	],
	CHOICES_PRESETS_MODES: [
		{ id: '0', label: 'Auto' },
		{ id: '1', label: 'Stereo' },
		{ id: '2', label: 'Direct' },
		{ id: '3', label: 'Dolby' },
		{ id: '4', label: 'DTS' },
		{ id: '5', label: 'All Stereo' },
		{ id: '6', label: 'Reference Stereo' },
		{ id: '7', label: 'Surround' },
	],
	CHOICES_PRESETS_SPEAKERS: [
		{ id: 'preset1', label: 'Preset 1' },
		{ id: 'preset2', label: 'Preset 2' },
		{ id: 'dirac', label: 'Dirac' },
	],
	CHOICES_ZONES: [
		{ id: 'zone1', label: 'Zone 1' },
		{ id: 'zone2', label: 'Zone 2' },
	],
	CHOICES_POWER_MODES: [
		{ id: 'power_on', label: 'On' },
		{ id: 'power_off', label: 'Off' },
	],
	DECREMENT_FIELD: {
		type: 'number',
		label: 'Decrement Amount (1-255)',
		id: 'val',
		min: 1,
		max: 255,
		default: 5,
		required: true,
		range: false,
	},
	INCREMENT_FIELD: {
		type: 'number',
		label: 'Increment Amount (1-255)',
		id: 'val',
		min: 1,
		max: 255,
		default: 5,
		required: true,
		range: false,
	},
	NUMERIC_FIELD: {
		type: 'number',
		label: 'Increment/Decrement Amount 0 - (+/-255)',
		id: 'amount',
		min: -255,
		max: 255,
		default: 5,
		required: true,
		range: false,
	},
	SOURCESELECT_FIELD: {
		type: 'dropdown',
		label: 'Source',
		id: 'sourceSelectDropdown',
		choices: [
			{ id: 'tuner', label: 'Tuner' },
			{ id: 'input_1', label: 'Input 1' },
			{ id: 'input_2', label: 'Input 2' },
			{ id: 'input_3', label: 'Input 3' },
			{ id: 'input_4', label: 'Input 4' },
			{ id: 'input_5', label: 'Input 5' },
			{ id: 'input_6', label: 'Input 6' },
			{ id: 'input_7', label: 'Input 7' },
			{ id: 'input_8', label: 'Input 8' },
		],
		default: 'Tuner',
	},
	SOURCEMODE_FIELD: {
		type: 'dropdown',
		label: 'Mode Preset',
		id: 'sourceModeDropdown',
		choices: [
			{ id: 'mode_ref_stereo', label: 'Reference Stereo' },
			{ id: 'mode_stereo', label: 'Stereo' },
			{ id: 'mode_music', label: 'Music' },
			{ id: 'mode_movie', label: 'Movie' },
			{ id: 'mode_direct', label: 'Direct' },
			{ id: 'mode_dolby', label: 'Dolby' },
			{ id: 'mode_dts', label: 'DTS' },
			{ id: 'mode_all_stereo', label: 'All Stereo' },
			{ id: 'mode_auto', label: 'Auto' },
			{ id: 'mode_surround', label: 'Surround' },
		],
	},
	POWERSELECT_FIELD: {
		type: 'dropdown',
		label: 'Power Mode',
		id: 'powerDropdown',
		choices: [
			{ id: 'power_on', label: 'On' },
			{ id: 'power_off', label: 'Off' },
		],
		default: 'power_on',
	},
	SPEAKERPRESET_FIELD: {
		type: 'dropdown',
		label: 'Speaker Preset',
		id: 'speakerPresetDropdown',
		choices: [
			{ id: 'preset1', label: 'Preset 1' },
			{ id: 'preset2', label: 'Preset 2' },
			{ id: 'dirac', label: 'Dirac' },
		],
	},
	ZONESELECT_FIELD: {
		type: 'dropdown',
		label: 'Zone',
		id: 'zoneDropdown',
		choices: [
			{ id: 'zone1', label: 'Zone 1' },
			{ id: 'zone2', label: 'Zone 2' },
		],
	},
	MONITORED_STATES: {
		power: '',
		volume: '',
		center: '',
		subwoofer: '',
		surround: '',
		back: '',
		source: '',
		mode: '',
		speaker_preset: '',
		tuner_band: '',
		tuner_channel: '',
		tuner_signal: '',
		tuner_program: '',
		tuner_RDS: '',
		audio_input: '',
		audio_bitstream: '',
		audio_bits: '',
		video_input: '',
		video_format: '',
		video_space: '',
		input_1: '',
		input_2: '',
		input_3: '',
		input_4: '',
		input_5: '',
		input_6: '',
		input_7: '',
		input_8: '',
	},
}
